### ISSUE TITLE
Jest test TypeError

### ISSUE THREAD

**Issue by tomsturge** [moxystudio/js-pico-signals#1]
Getting this error when running my components through Jest for snapshot tests
```
TypeError: pico_signals_1.default is not a function
```

Implementation as documented
```
import signal from 'pico-signals';

export const someSignal = signal();
```

**Comment by tomsturge** [comment]
Possible fix:

Instead of exporting
```
const createPicoSignals = () => new PicoSignals();

export default createPicoSignals;
```
export 
```
export default class PicoSignals {
  ...
}
```
and update implementation to:
```
import signal from 'pico-signals';

export const someSignal = new signal();
```

Would reduce the dependency size too

**Comment by satazor** [comment]
Thanks for submitting the issue.

The issue doesn't seem to be related to exporting a factory or the class directly. Even if we exported the class directly, the issue would be the same. Instead, it looks some miss-configuration of babel within Jest.

Could you go into the `node_modules/pico-signals` within your project, and write `console.log('cjs')` and `console.log('es')` at the top of `lib/index.js` and `es/index.js` respectively? Then, run the tests and see which one is printed and report back?

**Comment by tomsturge** [comment]
With `export const someSignal = signal();` the error was the same.

I changed it to `export const someSignal = signal;` and the tests passed and cjs was logged.

**Comment by satazor** [comment]
Could you provide a test case? I'm not able to reproduce the issue you are having.

For instance:

```js
// foo.js
import signal from '..';

export const someSignal = signal();
```

```js
// bar.js
import { someSignal } from './foo';

console.log(someSignal);
```

Is working as expected, even if I create those files in this project's `tests/` folder and import `bar.js` inside `index.test.js` and run `npm test` (which uses Jest).
